TangoSecret/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from TangoSecret import settings
from tangoschool.views import *
from django.urls import path, include

admin.site.site_header = "Админка Tango Secret"
admin.site.index_title = "Tango Secret"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tangoschool.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

tangoschool/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SchoolHome.as_view(), name='home'),
    path('login/', LoginUser.as_view(), name="login"),
    path('logout/', logout_user, name="logout"),
    path('add_student/', AddStudent.as_view(), name='add_student'),
    path('students/', StudentsList.as_view(), name='users_list'),
    path('student/<str:pk>/', ShowStudent.as_view(), name='student'),
    path('student/<str:pk>/buy_lessons/', BuyLessonsView.as_view(), name='buy_lessons'),
    path('add_lesson/', LessonCreateView.as_view(), name='add_lesson'),
    path('add_practice', PracticeCreateView.as_view(), name='add_practice'),
    path('lessons_view/', LessonsViews.as_view(), name='lessons_view'),
    path('lesson_view/<str:pk>/', LessonShow.as_view(), name='lesson'),
    # path('register/', RegisterUser.as_view(), name="register"),
    # path('student_update/', StudentUpdate.as_view(), name='user_update'),

]

tangoschool/models.py
from datetime import timedelta, datetime
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from jedi.inference.value import instance

LEVEL_CHOICES = (
    ('beginner', 'Початковий'),
    ('advanced', 'Продовжуючий'),
)


class TrainerProfile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='trainer_profile')
    email = models.EmailField(max_length=70, verbose_name="Пошта")
    birth_day = models.DateField(blank=True, null=True, verbose_name="День народження")
    phone_number = models.CharField(max_length=15, unique=True, blank=True, null=True, verbose_name="Номер телефону")
    description = models.TextField(blank=True, verbose_name="Опис")
    experience = models.PositiveIntegerField(blank=True, null=True, verbose_name="Стаж в танго")
    photo = models.ImageField(upload_to='trainers/', blank=True, null=True, verbose_name="фото")

    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренеры'

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name}'

    def get_absolute_url(self):
        return reverse('TrainerProfile-detail', args=[str(self.id)])


class Guest(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    first_name = models.CharField(max_length=255, verbose_name="Ім'я")
    last_name = models.CharField(max_length=255, verbose_name="Прізвище")
    email = models.EmailField(blank=True, verbose_name="Почта")
    phone_number = models.CharField(max_length=20, blank=True, verbose_name="Номер телефону")
    photo = models.ImageField(upload_to='students/', blank=True, null=True, verbose_name="фото")

    class Meta:
        verbose_name = "Гість"
        verbose_name_plural = "Гості"

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Account(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    balance = models.FloatField(blank=True, null=True, default=0, verbose_name="Залишок занять")

    class Meta:
        verbose_name = 'Обліковий запис'
        verbose_name_plural = 'Облікові записи'

    def __str__(self):
        students = ", ".join([str(student) for student in self.students.all()])
        return f"{students}"


class Operation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    operation_type = models.CharField(max_length=10, choices=[("buying", 'Покупка'), ('visiting', 'Посещение')],
                                      verbose_name="Операция с балансом")
    date = models.DateField(verbose_name="Дата операции")
    time = models.TimeField(verbose_name="Время операции")
    lesson_balance = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='operations')
    amount = models.FloatField(default=1, verbose_name="количество за раз")

    class Meta:
        verbose_name = 'Операція з балансом'
        verbose_name_plural = 'Операції з балансом'

    def student_name(self):
        names = self.lesson_balance.students.values_list('last_name', flat=True)
        return ', '.join(names)

    student_name.short_description = 'Студент'

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.now().date()  # Устанавливаем текущую дату, если она не указана
        if not self.time:
            self.time = datetime.now().time()  # Устанавливаем текущее время, если оно не указано
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Operation: {self.operation_type} - {self.date} - {self.student_name()}"


class Student(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    first_name = models.CharField(max_length=25, verbose_name="Ім'я")
    last_name = models.CharField(max_length=50, verbose_name="Прізвище")
    email = models.EmailField(max_length=70, null=True, blank=True, verbose_name="Пошта")
    birth_day = models.DateField(blank=True, null=True, verbose_name="День народження")
    phone_number = models.CharField(max_length=15, unique=True, blank=True, null=True, verbose_name="Номер телефону")
    photo = models.ImageField(upload_to='students/', blank=True, null=True, verbose_name="фото")
    level = models.CharField(max_length=30, choices=LEVEL_CHOICES,
                             blank=True, null=True, verbose_name="Рівень підготовки")
    is_active = models.BooleanField(default=True, verbose_name="Статус активності", editable=True)
    student_balance = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="students")

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'
        ordering = ['-is_active', 'level', 'last_name']

    def __str__(self):
        return f"{self.last_name} {self.first_name}  ({self.level}) "

    def get_absolute_url(self):
        return reverse('student', kwargs={'pk': self.id})



class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    lesson_topic = models.CharField(max_length=30, blank=True, null=True, verbose_name="Тема заняття")
    trainer1 = models.ForeignKey(TrainerProfile, on_delete=models.DO_NOTHING, null=True, blank=True,
                                 related_name='lessons_as_trainer1', verbose_name="Тренер 1")
    trainer2 = models.ForeignKey(TrainerProfile, on_delete=models.DO_NOTHING, null=True, blank=True,
                                 related_name='lessons_as_trainer2', verbose_name="Тренер 2")
    lesson_type = models.CharField(max_length=10, choices=(('full', 'Повне заняття'), ('practice', 'Практика')))
    students = models.ManyToManyField(Student, blank=True, verbose_name="Список учнів, записанных на заняття")
    guests = models.ManyToManyField(Guest, blank=True, verbose_name="Список гостей, записанных на заняття")
    date = models.DateField(verbose_name="Дата заняття")
    time = models.TimeField(verbose_name="Время заняття")
    level = models.CharField(max_length=30, choices=LEVEL_CHOICES, blank=True, null=True,
                             verbose_name="Рівень складності")
    guests_total_money = models.IntegerField(blank=True, default=0, verbose_name="Сумма від гостей")

    class Meta:
        verbose_name = "урок"
        verbose_name_plural = "уроки"
        ordering = ['-date', '-time']

    def __str__(self):
        return f"{self.date} {self.time} {self.lesson_type} "

    def get_absolute_url(self):
        return reverse('lesson', kwargs={'pk': self.id})

tangoschool/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LoginUserForm, AddStudentForm, AddLessonForm, BuyLessonsForm, AddPracticeForm
from .utils import *


class SchoolHome(DataMixin, TemplateView):
    template_name = 'tangoschool/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Танго Сикрет")
        return dict(list(context.items()) + list(c_def.items()))


class AddStudent(LoginRequiredMixin, DataMixin, CreateView):
    model = Student
    form_class = AddStudentForm
    template_name = 'tangoschool/student_add.html'
    success_url = reverse_lazy('users_list')

    def form_valid(self, form):
        balance_choice = form.cleaned_data.get('balance_choice')
        initial_balance = form.cleaned_data.get('initial_balance')

        if balance_choice == 'new':
            balance = Account.objects.create()
            if initial_balance:
                Operation.objects.create(
                    operation_type='buying',
                    lesson_balance=balance,
                    amount=initial_balance
                )

        else:
            existing_balance = form.cleaned_data.get('existing_balance').id
            balance = Account.objects.get(id=existing_balance)
            if initial_balance:
                Operation.objects.create(
                    operation_type='buying',
                    lesson_balance=balance,
                    amount=initial_balance
                )

        form.instance.student_balance = balance
        return super().form_valid(form)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Додати учня")
        return dict(list(context.items()) + list(c_def.items()))


class StudentsList(LoginRequiredMixin, DataMixin, ListView):
    model = Student
    template_name = 'tangoschool/students_list.html'
    context_object_name = 'students'
    login_url = reverse_lazy('home')

    def get_queryset(self):
        # Фильтруем учеников, у которых is_active=True
        return Student.objects.filter(is_active=True)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Список учнів")
        return dict(list(context.items()) + list(c_def.items()))


class ShowStudent(LoginRequiredMixin, DataMixin, DetailView):
    model = Student
    template_name = "tangoschool/student_show.html"
    context_object_name = 'student'

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Информація про учня")
        student = self.get_object()
        operations = student.student_balance.operations.all().order_by('-date', '-time')
        balance = student.student_balance
        balance_value = balance.balance
        context['balance'] = balance_value
        context['operations'] = operations
        return dict(list(context.items()) + list(c_def.items()))


class BuyLessonsView(DataMixin, View):
    template_name = 'tangoschool/buy_lessons.html'
    form_class = BuyLessonsForm

    def get(self, request, pk):
        student = Student.objects.get(pk=pk)
        context = {
            'title': f'Купівля занять для учня {student}',
            'form': self.form_class()
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        student = Student.objects.get(pk=pk)
        balance = student.student_balance
        form = self.form_class(request.POST)
        if form.is_valid():
            lessons = form.cleaned_data['lessons']
            if balance:
                Operation.objects.create(
                    operation_type='buying',
                    lesson_balance=balance,
                    amount=lessons
                )
                balance.save()
        else:
            existing_balance = form.cleaned_data.get('existing_balance').id
            Account.objects.get(id=existing_balance)
        return redirect('student', pk=pk)


class LessonCreateView(LoginRequiredMixin, DataMixin, CreateView):
    model = Lesson
    form_class = AddLessonForm
    template_name = 'tangoschool/lesson_create.html'
    success_url = reverse_lazy('lessons_view')

    def form_valid(self, form):
        lesson = form.save(commit=False)
        lesson.trainer1 = form.cleaned_data.get('trainer1')
        lesson.trainer2 = form.cleaned_data.get('trainer2')
        students = form.cleaned_data.get('students')
        lesson_level = form.cleaned_data.get('level')
        lesson.date = form.cleaned_data.get('date')
        lesson.time = form.cleaned_data.get('time')

        for student in students:
            balance = student.student_balance
            operation = Operation.objects.create(
                operation_type='visiting',
                lesson_balance=student.student_balance,
                amount=1,
                date=lesson.date,
                time=lesson.time
            )
            balance.save()
        create_and_send_excel_report()
        return super().form_valid(form)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Додати заняття")
        return dict(list(context.items()) + list(c_def.items()))


class PracticeCreateView(LoginRequiredMixin, DataMixin, CreateView):
    model = Lesson
    form_class = AddPracticeForm
    template_name = 'tangoschool/practice_create.html'
    success_url = reverse_lazy('lessons_view')

    def form_valid(self, form):
        lesson = form.save(commit=False)
        students = form.cleaned_data.get('students')
        guests = form.cleaned_data.get('guests')
        guests_total_money = len(guests) * 100

        for student in students:
            balance = student.student_balance
            operation = Operation.objects.create(
                operation_type='visiting',
                lesson_balance=student.student_balance,
                amount=0.5,
                date=lesson.date,
                time=lesson.time

            )
            balance.save()
        lesson.guests_total_money = guests_total_money
        create_and_send_excel_report()
        return super().form_valid(form)

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Додати практику")
        return dict(list(context.items()) + list(c_def.items()))


class LessonsViews(LoginRequiredMixin, DataMixin, ListView):
    model = Lesson
    template_name = 'tangoschool/lessons.html'
    context_object_name = 'lessons'

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Список занять")
        return dict(list(context.items()) + list(c_def.items()))


class LessonShow(LoginRequiredMixin, DataMixin, DetailView):
    model = Lesson
    template_name = "tangoschool/lesson_show.html"
    context_object_name = 'lesson'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lesson = self.get_object()
        students = lesson.students.all()
        guests = lesson.guests.all()
        context['students'] = students
        context['guests'] = guests
        c_def = self.get_user_context(title="Информаці про урок")
        return dict(list(context.items()) + list(c_def.items()))


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'tangoschool/login.html'

    def get_context_data(self, *, objects_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизація")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1> Страница не найдена </h1>')

# class StudentUpdate(LoginRequiredMixin, DataMixin, DetailView):
#     model = User#
#     form_class = UpdateUserForm
#     template_name = 'tangoschool/student_update.html'
#     success_url = reverse_lazy('home')
#     pk_url_kwarg = 'slug'

tangoschool/templates/tangoschool/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="/media/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/media/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/media/favicon_io/favicon-16x16.png">
    <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/bgvideo.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'images/logo.ico' %}" type="image/x-icon"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<div class="site-container">
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            {% block mainmenu %}
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="mainmenu">
                    <li class="logo"><a href="{% url 'home' %}">
                        <div class="logo"></div>
                    </a></li>

                    {% for m in menu %}
                        <li class="nav-item"><a href='{% url m.url_name %}'>{{ m.title }}</a></li>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_staff %}
                            <li><a href="/admin/">Админ</a></li>
                        {% endif %}
                        <li class="last"> {{ user.username }} | <a href="{% url 'logout' %}">Выйти</a></li>
                    {% else %}
                        <li class="last"><a href='{% url 'login' %}'>Войти</a>
                        </li>
                    {% endif %}
                </ul>
            {% endblock mainmenu %}
            </div>
        </nav>
    </header>
    {% block content %}


        <div class="bgvideo">
            <video src="/media/-12127.mp4" type="video/mp4" autoplay muted loop></video>
            <div class="video-text">
                <h1>Future's here </h1>
            </div>
        </div>

        <div class="site-content">
        <div class="container-fluid mt-4">
            <div class="row">
                <div class="col-lg-1">

                </div>

                <div class="col-lg-12 col-md-12">
                    <div class="row">

                        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
                            <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleIndicators"
                                        data-bs-slide-to="0"
                                        class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleIndicators"
                                        data-bs-slide-to="1"
                                        aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleIndicators"
                                        data-bs-slide-to="2"
                                        aria-label="Slide 3"></button>
                                <button type="button" data-bs-target="#carouselExampleIndicators"
                                        data-bs-slide-to="3"
                                        aria-label="Slide 4"></button>
                            </div>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <div class="d-block w-100">
                                        <div class="row justify-content-center text-center">
                                            <div class="col-lg-6 col-md-6 mx-auto">
                                                <img src="/media/200067800188_95015.jpg" class="w-100 max-img-size"
                                                     alt="...">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="d-block w-100">
                                        <div class="row justify-content-center text-center">
                                            <div class="col-lg-6 col-md-6 mx-auto">
                                                <img src="/media/FB_IMG_1504415960242.jpg" class="w-100 max-img-size"
                                                     alt="...">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="d-block w-100">
                                        <div class="row justify-content-center text-center">
                                            <div class="col-lg-6 col-md-6 mx-auto">
                                                <img src="/media/FB_IMG_1643784668192.jpg" class="w-100 max-img-size"
                                                     alt="...">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <div class="d-block w-100">
                                        <div class="row justify-content-center text-center">
                                            <div class="col-lg-6 col-md-6 mx-auto">
                                                <img src="/media/FB_IMG_1643784747674.jpg" class="w-100 max-img-size"
                                                     alt="...">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button class="carousel-control-prev" type="button"
                                    data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button"
                                    data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>


                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 text-center mt-4">
                                <button type="button" class="btn btn-primary btn-lg my-4">See more</button>
                            </div>
                            <div class="col-lg-12 col-md-12 text-center mt-4">
                                <p>Can we help you?</p>
                            </div>
                            <div class="col-lg-12 col-md-12 text-center">
                                <img class="call-anim" style="width: 30px;" src="/media/images.jfif" alt="...">
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>

    {% endblock content %}
    </div>

    <footer class="mt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-12 footer-text text-center">
                    <p>All Rigts Reserved 2022</p>
                </div>
                <div class="col-lg-4 col-md-12 footer-text text-center">
                        <p>Контакти <br>Розклад</br> Наша Адреса</p>
                </div>
                <div class="col-lg-4 col-md-12 media-links">
                    <img style="width: 60px; margin-inline: 1em;" src="/media/ytb.jfif" alt="...">
                    <img style="width: 60px; margin-inline: 1em;" src="/media/tgm.jfif" alt="...">
                </div>
            </div>
        </div>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

</body>
</html>

tangoschool/templates/tangoschool/buy_lessons.html
{% extends 'tangoschool/base.html' %}

{% block content %}
<h1> {{ title }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Додати заняття</button>
</form>
{% endblock %}

tangoschool/templates/tangoschool/index.html
{% extends 'tangoschool/base.html' %}

tangoschool/templates/tangoschool/lesson_create.html
{% extends 'tangoschool/base.html' %}
{% load static %}
{% block content %}
    <h1>Создать урок</h1>

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти</button>
    </form>
    <script src="{% static 'js/script.js' %}"></script>

{% endblock %}

tangoschool/templates/tangoschool/lesson_show.html
{% extends 'tangoschool/base.html' %}

{% block content %}
<h1> {{ title }}</h1>


    <h2> Дата: {{ lesson.date }} </h2>
    <h2> Час {{ lesson.time }} </h2>
    {% if lesson.lesson_type %}
    <h2>Тип уроку: {{ lesson.get_lesson_type_display }}</h2>
    {% endif %}
    {% if lesson.level %}
       <h2> Ріень: {{ lesson.get_level_display }}</h2>
    {% endif %}
    {% if lesson.trainer1 %}
    <h2>Тренер 1: {{ lesson.trainer1 }} </h2>
    {% endif %}
    {% if lesson.trainer2 %}
    <h2>Тренер 2: {{ lesson.trainer2 }} </h2>
    {% endif %}
    {% if lesson.lesson_topic %}
    <h2>Тема уроку:{{ lesson.lesson_topic }}</h2>
    {% endif %}

   <hr>

    <h1> Студенти:</h1>
    {% for student in students %}
      <h3> {{ forloop.counter }}. {{ student }} </h3>

   {% endfor %}
    <hr>

    {% if guests %}
<h1> Гости </h1>
    {% for guest in guests %}
    <h3> {{ forloop.counter }}. {{ guest }} </h3>

    {% endfor %}
     <h2>Сумма від гостей: {{ lesson.guests_total_money }}</h2>
    {% endif %}
{% endblock %}

tangoschool/templates/tangoschool/lessons.html
{% extends 'tangoschool/base.html' %}

{% block content %}
    <h2>{{ title }}</h2>
    <ul class="list-articles">
        <h5>
            <span style="display: inline-block; width: 270px;"> Дата</span>
            <span style="display: inline-block; width: 100px;">Час</span>
            <span style="display: inline-block; width: 150px;">Тип заняття</span>
            <span style="display: inline-block; width: 150px;">Рівень</span>
            <span style="display: inline-block; width: 200px;">Тренер 1</span>
            <span style="display: inline-block; width: 200px;">Тренер 2</span>
            <span>Тема заняття</span>
        </h5>


        {% for ls in lessons %}
            <li>
                <div class="article-panel">
                    <a href="{{ ls.get_absolute_url }}">
                        {% if ls.lesson_type == 'full' %}
                            <h5>
                                <span style="display: inline-block; width: 270px;">{{ ls.date|date:"d.m.Y (D)" }}</span>
                                <span style="display: inline-block; width: 100px;">{{ ls.time }}</span>
                                <span style="display: inline-block; width: 150px;">{{ ls.get_lesson_type_display }}</span>
                                <span style="display: inline-block; width: 150px;">{{ ls.get_level_display }}</span>
                                <span style="display: inline-block; width: 200px;">{{ ls.trainer2 }}</span>
                                <span style="display: inline-block; width: 200px;">{{ ls.trainer1 }}</span>
                                <span>{{ ls.lesson_topic }}</span>
                            </h5>
                        {% else %}
                            <h5>
                                <span style="display: inline-block; width: 270px;">{{ ls.date|date:"d.m.Y (D)" }}</span>
                                <span style="display: inline-block; width: 100px;">{{ ls.time }}</span>
                                <span style="display: inline-block; width: 150px;">{{ ls.get_lesson_type_display }}</span>
                            </h5>
                        {% endif %}
                    </a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

tangoschool/templates/tangoschool/login.html
{% extends 'tangoschool/base.html' %}
{% block content %}
    <h1> {{ title }}</h1>
    <form method="post">
    {% csrf_token %}
    <div class="form-error"> {{ form.non_field_errors }}</div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }} </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Увійти</button>

    </form>

{% endblock content %}

tangoschool/templates/tangoschool/student_show.html
{% extends 'tangoschool/base.html' %}

{% block content %}
<h1> {{ title }}</h1>
    {% if student.photo %}
    <div class="image-container">
                            <img class="img-article-student" src="{{ student.photo.url }}" alt="фото">
                        </div>
    {% endif %}

    <h2>{{ student.last_name }}  {{ student.first_name }}</h2>
    <h3>День народження -  {{ student.birth_day }}</h3>
    <h3>Рівень -  {{ student.level }}</h3>
    <h3>Залишок занять -  {{  student.student_balance.balance }}</h3>
    <a href="{% url 'buy_lessons' pk=student.pk %}" class="btn btn-primary">Додати заняття</a>
     <h2>Список операцій з балансом:</h2>
    <ul>
        {% for operation in operations %}
            <li>{{ operation.get_operation_type_display }} - {{ operation.date|date:"d.m.Y (D)" }} {{operation.time }}</li>
        {% endfor %}
    </ul>
{% endblock %}